In [62]:
import pygame
import pygame_gui
import sys
import numpy as np

In [63]:
initial_board = np.array([
    [4, 6, 7, 1, 2, 7, 6, 4],
    [ 10, 10, 10, 10, 10, 10, 10, 10 ],
    [ 0, 0, 0, 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0, 0, 0, 0 ],
    [ 20, 20, 20, 20, 20, 20, 20, 20 ],
    [ 14, 16, 17, 11, 12, 17, 16, 14 ],
])

In [64]:
# piece id to sprite id
def pid_sid(id):
    assert id in range(1, 21), "Piece ID must be between 0 and 20."
    if id > 10:
        id -= 10
        i = 6
    else:
        i = 0

    if id == 1:
        j = 0
    elif id == 2 or id == 3:
        j = 1
    elif id == 4 or id == 5:
        j = 2
    elif id == 6:
        j = 3
    elif id == 7:
        j = 4
    elif id == 8 or id == 9 or id == 10:
        j = 5
    else:
        assert False, "Logic error."

    return i + j

In [73]:
# Initialize Pygame
pygame.init()

# Constants
WIDTH, HEIGHT = 400, 400
TILE_SIZE = WIDTH // 8

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Game data
board = initial_board.copy()
print(board)

# Load sprite sheet
spritesheet = pygame.image.load('ChessPiecesArray.png')
(SSw, SSh) = spritesheet.get_size()
Sd = SSh // 2
white_pawn = spritesheet.subsurface(pygame.Rect(5*Sd, 1*Sd, Sd, Sd))
#print(sprites.get_size())

sprite_size = spritesheet.get_size()[1]//2
# sprites = [
#     [ pygame.transform.scale(
#         spritesheet.subsurface(pygame.Rect(j*sprite_size, i*sprite_size, sprite_size, sprite_size)), # Surface of (i, j)-th sprite
#         (TILE_SIZE, TILE_SIZE) # size to resize to
#     ) for j in range(6)
#     ] for i in range(2)
# ]

# sprites = [
#     pygame.transform.scale(
#         spritesheet.subsurface(pygame.Rect(j*sprite_size, i*sprite_size, sprite_size, sprite_size)), # Surface of (i, j)-th sprite
#         (TILE_SIZE, TILE_SIZE) # size to resize to
#     ) for j in range(6) for i in range(2)
# ]

sprites = [
    pygame.transform.scale(
        spritesheet.subsurface(pygame.Rect(j*sprite_size, i*sprite_size, sprite_size, sprite_size)), # Surface of (i, j)-th sprite
        (TILE_SIZE, TILE_SIZE) # size to resize to
    ) for i in range(2) for j in range(6)
]


print(len(sprites))


# Initialize the screen
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Simple Chess")

cursor = (0, 0)

def pos_pix(pos):
    (r, c) = pos
    return (TILE_SIZE*r, TILE_SIZE*c)

# Main game loop
running = True
while running:    
    for event in pygame.event.get():
        #if event.type == pygame.QUIT:
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
                continue
            elif event.key == pygame.K_UP:    
                cursor = (cursor[0], cursor[1]-1)
            elif event.key == pygame.K_DOWN:
                cursor = (cursor[0], cursor[1]+1)
            elif event.key == pygame.K_LEFT:
                cursor = (cursor[0]-1, cursor[1])
            elif event.key == pygame.K_RIGHT:
                cursor = (cursor[0]+1, cursor[1])
        elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:  # Left mouse button click
            x, y = event.pos
            ccol = x // TILE_SIZE
            crow = y // TILE_SIZE
            print(f"Clicked on tile: ({ccol}, {crow})")
            cursor = (ccol, crow)

    cursor_good = (TILE_SIZE*cursor[0], TILE_SIZE*cursor[1])


    # Draw chess board
    for row in range(8):
        for col in range(8):
            #color = WHITE if (row + col) % 2 == 0 else BLACK
            color = (0xd1, 0xe3, 0xff) if (row + col) % 2 == 0 else (0x57, 0x97, 0xff)
            if (row, col) == cursor:
                #R, G, B = color
                color = (0x57, 0xff, 0xbb)
            pygame.draw.rect(screen, color, (col * TILE_SIZE, row * TILE_SIZE, TILE_SIZE, TILE_SIZE))
            if board[row][col] in range(1, 21):
                #screen.blit(sprites[pid_sid(board[row][col])], pos_pix((row, col)))
                screen.blit(sprites[pid_sid(board[row][col])], pos_pix((col, row)))

                
                
    
    # for i in range(2):
    #     for j in range(6):
    #         screen.blit(sprites[i*6+j], (TILE_SIZE*j, TILE_SIZE*i))


    #screen.blit(sprites, (100,100))
    #screen.blit(sprites, sprites.get_rect())
    #screen.blit(pygame.transform.scale(white_pawn, (TILE_SIZE, TILE_SIZE)), (TILE_SIZE*cursor[0], TILE_SIZE*cursor[1]))
    
    screen.blit(sprites[6+5], (cursor_good[0], cursor_good[1]))
    
    pygame.display.flip()


pygame.quit()
#sys.exit()        


[[ 4  6  7  1  2  7  6  4]
 [10 10 10 10 10 10 10 10]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [20 20 20 20 20 20 20 20]
 [14 16 17 11 12 17 16 14]]
12
Clicked on tile: (3, 3)
Clicked on tile: (3, 4)
Clicked on tile: (5, 3)
Clicked on tile: (3, 5)
Clicked on tile: (4, 4)
